# --------------------------------------------------
# DS1000Z-ScopeInterface
# --------------------------------------------------

[workflows]

[workflows.default]

# Set horizontal scale (seconds / horizontal division)
timebase = 0.0005

# Set vertical scale (volts / vertical division)
scale = 1.00

# Set horizontal position (in seconds)
horizontal_position = 0.00

# Set channel vertical position (in volts)
vertical_position = 0.00

# Set trigger level in volts
trigger_level = 1.00
